### ISSUE TITLE
Directory containing plane embedding dataset

### ISSUE THREAD

**Issue by zhenpeiyang** [samiragarwala/PlaneFormers#2]
Thank you for the great work!

I am trying to run your training code, but was unable to find script to setup your dataset. Could you elaborate more? Thanks!

**Comment by samiragarwala** [comment]
Thank you for reaching out! We use the same dataset as [SparsePlanes](https://jinlinyi.github.io/SparsePlanes/) for training our model and evaluating it in the two view case. Please refer to their [repository](https://github.com/jinlinyi/SparsePlanes/blob/main/docs/data.md) for details on downloading the raw images and annotation files.

An additional step required for training this model is extracting and saving plane embeddings which is done by running the PlaneRCNN from SparsePlanes on the images in the above dataset. Please refer to the [attached file](https://github.com/samiragarwala/PlaneFormers/files/9397729/create_dataset.zip) to see how we did that and the format for saving the embeddings.

After downloading the annotations and saving the embeddings, you should be able to run the training code using `train.py` with the correct paths for the annotation file folder and the embedding dataset folder specified in `--json_path` and `--path` respectively.
