### ISSUE TITLE
Dataset download links in SparsePlanes repo seem extremely slow

### ISSUE THREAD

**Issue by Pushkar2307** [samiragarwala/PlaneFormers#4]
Hi Samir, thanks for sharing this amazing work!

The dataset download links on the SparsePlanes repo are extremely slow for me. I tried on multiple networks.

Is there an alternative link to download the dataset?

Thanks,
Pushkar

**Comment by samiragarwala** [comment]
Hi Pushkar, thanks for reaching out! I just checked the SparsePlanes repository and it seems the authors have updated the links as mentioned in `https://github.com/jinlinyi/SparsePlanes/issues/8`. Thanks!
